### ISSUE TITLE
[Crash]: Fabric Transfer API Crash

### ISSUE THREAD

**Issue by TheStaticVoid** [MattiDragon/ExtendedDrawers#66] opened 2023-06-08 07:38 UTC
### Description of the issue

Hello,

We're experiencing a bug when outputing items into a Compacting Drawer. Initially I thought it might be an issue with Modern Industrialization, but after reaching out to Technici4n he said it is most likely a bug with how this mod interacts with the transfer API.

### Reproduction steps

These are the steps to recreate the scenario I found the blocks in when the crash occurred, I've been unable to fully replicate the issue though.
1. Place an MI Item Output Hatch facing into a Compacting Drawer
2. Enable auto extract mode in the Item Output Hatch
3. When recipes complete and attempt to push into the Compacting Drawer, the crash occurs (or so I believe)

### Mod version

1.4.1

### Operating System

Windows 10

### Minecraft version

1.19.2

### Other mods

Modern Industrialization 1.6.9
Fabric API 0.76.0
Cloth Config 8.2.88

### Server

Happens

### Client

Happens

### Logs

https://pastebin.com/raw/XVdNe3u3

### Crash Report

https://pastebin.com/raw/gHtBZ7iW

**Comment by kevintok** [comment] 2023-06-08 20:23
Not sure if this is related but it was running fine before for some time. This happened not too long after I added drawer downgrade to the compacting drawer.

**Comment by kevintok** [comment] 2023-06-17 23:31
It's definitely related, for some reason compacting drawer with drawer downgrade can have more than the item limit inserted into it. I think the subsequent insert crashes because the compacting drawer returned a negative value for available slot.

**Comment by TheStaticVoid** [comment] 2023-06-19 02:06
New crash related to pulling items from drawers. This time it was a Create Andesite Funnel pulling from a 1x1 Drawer locked to logs. As soon as the funnel is placed the server crashes.

Crash report: https://pastebin.com/ZLtehkLS
Image of the setup:
![image](https://github.com/MattiDragon/ExtendedDrawers/assets/6089108/d52a25c8-2c94-43d3-bea4-5195a24b3235)
As soon as the funnel is placed on the right of the drawer the server crashes.

**Comment by MattiDragon** [comment] 2023-06-19 17:05
@TheStaticVoid I've debugged the create crash. It's caused be create not liking storages with a type, but no items actually inside, will report.

**Comment by MattiDragon** [comment] 2023-06-20 10:55
I finally got debugging working with MI. I can't reproduce the crash. If you have more precise and reliable steps then I can try again. I'll add in some safeguards and logging in case something does go wrong so that it's easier to debug from a log.

**Comment by MattiDragon** [comment] 2023-06-25 08:40
I figured out what's wrong, will be fixed next update

**Closed as completed** 2023-06-25 09:18 UTC
Labels: crash, confirmed, fixed

**Comment by TheStaticVoid** [comment] 2023-06-25 14:42
Awesome thank you for looking into this more.
