### ISSUE TITLE
[Bug]: Serious item deletion and duplication bug

### ISSUE THREAD

**Issue by ghost** [MattiDragon/ExtendedDrawers#17] opened 2022-08-02 23:45 UTC
### Description of the issue

When breaking a drawer that contains items, if you have the same drawer type in your inventory, the drawers will merge and delete the data for the drawer. Similarly, if you pick up drawers of the same type with a drawer that contains data, the data will duplicate across all the drawers.

### Reproduction steps

**Deletion**
1. Place any drawer
2. Put items in the drawer
3. Break the drawer with the same drawer type in your inventory
4. Pickup the drawer
5. Data is deleted

**Duplication**
1. Place any drawer
2. Put items in the drawer
3. Drop other drawers of the same type on the ground
4. Break the drawer
5. Pickup the drawer
6. Pickup the other drawers on the ground
7. Data is duplicated

### Mod version

v1.3.2

### Operating System

Windows 10

### Minecraft version

1.19

### Other mods

Fabric API 0.58.0

### Server

Not tested

### Client

Happens

### Logs

Irrelevant

**Comment by MattiDragon** [comment] 2022-08-03 07:45
I'm unable to reproduce. Do you have any mods that you haven't mentioned installed?

**Comment by ghost** [comment] 2022-08-03 12:56
> I'm unable to reproduce. Do you have any mods that you haven't mentioned installed?

A handful yes but none of them mess with inventory or item stacking or lore, I'm seeing if I can find a minimum case now but it may take me a bit. Sorry for the hassle.

**Comment by MattiDragon** [comment] 2022-08-03 14:52
I though the template specifically asked you to find a minimal test case? I won't be able to fix an issue that doesn't happen with the mods provided

**Comment by MattiDragon** [comment] 2022-08-07 06:36
How's it going with the minimum test case?

**Comment by MattiDragon** [comment] 2022-09-23 10:04
Hey! I'm closing the issue until you can get me a minimal test case as it being open doesn't help anyone

**Closed as not planned** 2022-09-23 10:04 UTC
Labels: incomplete, bug, unconfirmed

**Comment by QianFuv** [comment] 2023-05-16 05:12
mod list https://moddermore.net/list/o_R7BqcLo_6H
I'm looking for the smallest test sample.
