### ISSUE TITLE
[Bug]: Load order dependent mixin conflict with QSL

### ISSUE THREAD

**Issue by CarlMichaelFabe** [MattiDragon/ExtendedDrawers#88] opened 2024-01-02 18:02 UTC
### Description of the issue

With both `Supplementaries` and `Friends and Foes` installed, somehow the compacting drawer doesn't compact clay into clay blocks anymore.
This also happens with `You've Goat to be Kidding Me` mod.

![293703326-fac57b28-3187-49af-9e61-b5c9c6f93577](https://github.com/MattiDragon/ExtendedDrawers/assets/116660522/5e09d32a-e19f-47ff-87fc-461e08bbd5a2)

I observed this happening in 2 environments. Written in the **Other mods** section below.

### Reproduction steps

1. Install mods specified in either environment
2. Put clay inside compacting drawer

### Mod version

2.1.0

### Operating System

Windows 11

### Minecraft version

1.20.1

### Other mods

Environment 1
- QFAPI `7.4.0_qsl-6.1.2_fapi-0.90.0_mc-1.20.1`
- Quilt Kotlin Libs `2.1.3+kt.1.9.10+flk.1.10.10`
- Extended Drawers `2.1.0+mc.1.20.1`
- Friends and Foes `1.20.1-2.0.6`
- Moonlight `1.20-2.8.79-fabric`
- Supplementaries `1.20-2.7.17-fabric`

Environment 2
- QFAPI `7.4.0_qsl-6.1.2_fapi-0.90.0_mc-1.20.1`
- Quilt Kotlin Libs `2.1.3+kt.1.9.10+flk.1.10.10`
- Extended Drawers `2.1.0+mc.1.20.1`
- Moonlight `1.20-2.8.78-fabric`
- You've Goat to be Kidding Me `1.20-1.3.4`

### Server

Happens

### Client

Happens

### Logs

No crash

**Comment by MattiDragon** [comment] 2024-01-03 07:46
What's interesting here is that the compacting recipe for clay is manually added instead of being generated from recipes. For environment 1, are you sure both are required?

**Comment by encode42** [comment] 2024-01-05 06:53
I've tested in another environment to narrow things down! The issue still occurs when only Moonlight Lib is installed.
- Extended Drawers `2.1.0+mc.1.20.1`
- Moonlight `1.20-2.8.80-fabric`
- Quilt Kotlin Libs `2.1.3+kt.1.9.10+flk.1.10.10`
- QFAPI `7.4.0+0.90.0-1.20.1`
- Quilt Loader `0.23.0-beta.1`

![image](https://github.com/MattiDragon/ExtendedDrawers/assets/34699884/c9ec7349-521a-4f49-8930-72fca04c2ab7)

**Comment by MattiDragon** [comment] 2024-01-05 07:59
Thanks, this will help a lot with debugging

**Comment by MattiDragon** [comment] 2024-01-05 15:38
Update: seems like moonlight lib isn't the issue. Right now looking like QKL is somehow at fault

**Comment by MattiDragon** [comment] 2024-01-05 15:54
Figured it out. This is a mod load order dependent mixin incompatibility with QSL. I think you can temporarily fix this by using jvm args to force extended drawers to load before qsl (or the other way, not sure)

**Comment by CarlMichaelFabe** [comment] 2024-01-07 03:19
Sorry for the late reply.

> For environment 1, are you sure both are required?

From the time I tested it, yes both were required. With only `Supplementaries` and `Moonlight Lib` installed, there were no issues, Same with only `Friends and Foes`.
Though it seems `Supplementaries` and `Moonlight Lib` have both been updated, so I don't know if it still works in that environment.


> Figured it out. This is a mod load order dependent mixin incompatibility with QSL. I think you can temporarily fix this by using jvm args to force extended drawers to load before qsl (or the other way, not sure)

For now, I think I'll just manually add the upacking recipe for clay as a workaround. Changing the mod load order seems a bit too much for me atm and it might mess other things up.

But still, thank you for your time! You can close this now if you want.

**Comment by MattiDragon** [comment] 2024-01-07 12:30
I'll close this myself once the issue is solved

**Comment by MattiDragon** [comment] 2024-01-10 15:02
Update with a fix releasing soon

**Closed as completed by MattiDragon** 2024-01-10 15:02 UTC
Labels: bug, confirmed, other mod
