### ISSUE TITLE
[Bug]: Drawers cannot break from the front

### ISSUE THREAD

**Issue by muhammedesadcomert** [MattiDragon/ExtendedDrawers#50] opened 2023-04-16 22:17 UTC
### Description of the issue

Drawers cannot break from their front side. This problem is the same as #35. Idk why you actually closed this while the problem still existed.

### Reproduction steps

1. Place a drawer.
2. Try to break it from the front side.

### Mod version

1.3.9

### Operating System

Windows 11

### Minecraft version

1.19.2

### Other mods

- architectury 6.5.77
- cloth-config 8.2.88
- extended_drawers 1.3.9+mc.1.19.2
- fabric-api 0.76.0+1.19.2
- modmenu 4.2.0-beta.2
- roughlyenoughitems 9.1.595
- jade 8.7.3

### Server

Not tested

### Client

Happens

### Logs

https://mclo.gs/aN6szK0

### Extra Context

A short video of the bug: https://youtu.be/huissP2lg_g

_I think the problem is while trying to break the drawer from the front side it tries to give to the player an item even if is empty._

**Comment by MattiDragon** [comment] 2023-04-17 17:22
I've found a fix, but I probably won't do a full release just for this one bug. You can set the `creativeExtractionMode` config option to `front_mine` as a temporary fix. It's probably nicer that way anyways

**Comment by muhammedesadcomert** [comment] 2023-04-17 17:59
@MattiDragon What's wrong with a full release, some modders publish more than one release in a day for small changes.

I am confused. This bug happens in the survival mod. Isn't that option changing only creative mod behavior?

**Comment by MattiDragon** [comment] 2023-04-17 18:05
The bug is caused by the creative mode changes firing even when in survival. I could do a release, but it's a bit of work as I have to port the fixes to all supported versions. Automatic releases does make it easier but still takes a bit of work. I was also thinking about redoing the config system as it's kind of jank.

**Comment by muhammedesadcomert** [comment] 2023-04-17 18:42
Ok, this is fair. I hadn't thought of other versions. I can go with the temporary fix until the update, no problem.

You know what they say, "Out with the jank, in with the swank!" Good luck with it!

**Comment by MattiDragon** [comment] 2023-05-02 15:48
Resolved in 1.3.10

**Closed as completed by MattiDragon** 2023-05-02 15:48 UTC
Labels: bug, confirmed, fixed
