### ISSUE TITLE
[Bug 1.18.2] Crash when placing enchanted sword in drawer

### ISSUE THREAD

**Issue by itsdinkd** [MattiDragon/ExtendedDrawers#4] opened 2022-06-13 22:31 UTC
### Description of the issue

Occuring on Another Quality Modpack 2.

Looks like there is a coxinha utilities wooden hopper also involved that the player is using associated with a extended drawer. 

![image](https://user-images.githubusercontent.com/35115304/173457787-42c95b08-1b91-4a65-b44f-7eaaaccc6b47.png)

### Reproduction steps

Put an enchanted sword into a drawer
Crash

### Mod version

1.2.1

### Operating System

linux

### Minecraft version

1.18.2

### Other mods

see crash report

### Server

Happens

### Client

Not tested

### Logs

https://gist.github.com/itsdinkd/c8d4c5829a95e5098f51eb7214987029

**Comment by MattiDragon** [comment] 2022-06-15 13:11
Seems like the LibBlockAttributes transfer api compat is broken. Will ask the if they know anything about this.

**Comment by AlexIIL** [comment] 2022-06-15 15:37
From a brief look, it *might* be caused by the identity check here:
https://github.com/MattiDragon/ExtendedDrawers/blob/d40cd1b1314d297c4b71a27da7cd353d6dac43b2/src/main/java/io/github/mattidragon/extendeddrawers/drawer/DrawerSlot.java#L52
As far as I'm aware, transfer API doesn't cache `ItemVariant`s that have NBT \[1\], so you'd need to use `.equals()` here rather than an identity check.


\[1\]: https://github.com/FabricMC/fabric/blob/d78c70fcbb5ccb10a51a6728a3565e04ee86d1c7/fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/item/ItemVariantImpl.java#L36-L45

**Comment by AlexIIL** [comment] 2022-06-15 15:48
For context, LBA (like forge) is simulation based, which means it needs to simulate the extraction before actually extracting it - there's two methods in LBA relevant here ([ItemInvUtil.move(4 args)](https://github.com/AlexIIL/LibBlockAttributes/blob/f21ad315e4f998072cdb4b129d089c531ab633db/src/main/java/alexiil/mc/lib/attributes/item/ItemInvUtil.java#L99-L137), and [TransferItemApiCompat.Transfer2Lba.attemptExtraction()](https://github.com/AlexIIL/LibBlockAttributes/blob/f21ad315e4f998072cdb4b129d089c531ab633db/src/main/java/alexiil/mc/lib/attributes/item/compat/mod/transfer/TransferItemApiCompat.java#L153-L197))

1: It passes the `ItemVariant` that it found in the inventory back to the inventory (so it can extract successfully the first time)
2: It then creates a new `ItemVariant` based on the exact `ItemStack` found - for enchanted tools this will have NBT, and so won't be the same object - which will probably fail the identity check in ExtendedDrawers.

**Comment by MattiDragon** [comment] 2022-06-15 15:50
That does indeed seem to be the issue. I'd suggest maybe not crashing when that happens, but I will fix it on my end in a few days when I have time.

**Comment by Technici4n** [comment] 2022-06-16 08:02
Yes @AlexIIL is right here, variants should never be compared with ==.

As for crashing, it's probably better to silently void items, but crashing is rare enough atm that it's fine.

**Comment by MattiDragon** [comment] 2022-06-18 09:19
Could you check if [this version](https://github.com/MattiDragon/ExtendedDrawers/releases/download/dev/ExtendedDrawers-1.2.2-dev.36+mc.1.18.2.jar) fixes it?

**Comment by MattiDragon** [comment] 2022-06-23 14:59
Closing this now. If the issue persists please reopen

**Closed by MattiDragon** 2022-06-23 14:59 UTC
Labels: bug, mod compatablity, accepted, next release
