### ISSUE TITLE
[Bug]: The drawer can be placed into the shulker box through a funnel.

### ISSUE THREAD

**Issue by QianFuv** [MattiDragon/ExtendedDrawers#57] opened 2023-05-16 09:30 UTC
### Description of the issue

The drawer mod is designed so that drawers that function like shulker boxes cannot be put into Shulker boxes
<img width="380" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/7566da55-0b4a-460d-896a-87d5685a1228">
But through the funnel, the drawer can be fed into the shulker box
<img width="360" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/c81b67a7-9e7b-40b7-a49a-abbae7719c3e">

### Reproduction steps

https://github.com/Qian-F/QFserver-Wonder/issues/4#issue-1711573462

### Mod version

1.3.6

### Operating System

win11

### Minecraft version

1.18.2

### Other mods

none

### Server

Happens

### Client

Happens

### Logs

no more

**Comment by MattiDragon** [comment] 2023-05-16 11:02
By funnel do you mean hopper, a create funnel or something else?

**Comment by QianFuv** [comment] 2023-05-16 11:39
> By funnel do you mean hopper, a create funnel or something else? 

just hopper ，the vanilla Hopper

**Comment by MattiDragon** [comment] 2023-05-16 13:28
Just reproduced this. Turns out, vanilla doesn't check if an item is nestable when hoppers try to insert into a shulker box. It instead checks if the items is a shulker box for some reason.

**Comment by QianFuv** [comment] 2023-05-16 14:21
> Just reproduced this. Turns out, vanilla doesn't check if an item is nestable when hoppers try to insert into a shulker box. It instead checks if the items is a shulker box for some reason.

can you make a 1.18.2 version?

**Comment by QianFuv** [comment] 2023-05-16 14:26
i think it is a huge bug

**Comment by MattiDragon** [comment] 2023-05-16 16:39
I'll update the 1.18.2 with this specifically

**Comment by QianFuv** [comment] 2023-05-16 16:57
thank you！！！

**Comment by QianFuv** [comment] 2023-05-17 08:46
> I'll update the 1.18.2 with this specifically

Sorry to bother you, but could you give me an update approximate time?
In the meantime, I think you should look at another issue: https://github.com/MattiDragon/ExtendedDrawers/issues/56
This is a historical issue (I checked the time all afternoon) that should be fixed.

**Comment by MattiDragon** [comment] 2023-05-17 13:45
I've just finished the port. I'll release the updates soon. Your other issue won't be fixed by me. See my comment for more details.

**Closed as completed** 2023-05-17 13:47 UTC
Labels: bug, confirmed, fixed
