### ISSUE TITLE
[Bug]: Drawers create a lot of lag

### ISSUE THREAD

**Issue by TheButterbrotMan** [MattiDragon/ExtendedDrawers#6] opened 2022-06-19 17:36 UTC
### Description of the issue

I made a mid sized storage room of about 160-180 drawers to upgrade my storage system, when putting in items or grabing them from drawers the server shit itself. I just realized that the common lag spikes happen a lot more offten when there are more players... maybe this is the cause of the general lag.

### Reproduction steps

1. Setup a mid sized storage system.
2. Use Drawers
3. ???
4. Profit

### Mod version

ExtendedDrawers-1.2.1+mc.1.18.2

### Operating System

Windows 10

### Minecraft version

1.18.2

### Other mods

[ww](https://www.curseforge.com/minecraft/modpacks/deathdusk) (2.0.10)

### Server

Happens

### Client

Not tested

### Logs

No log available

### Extra Context

Spark when problem apears: 
![unknown](https://user-images.githubusercontent.com/64548098/174493516-d6e23588-18c3-4dea-adf6-b675dca2d178.png)

**Comment by MattiDragon** [comment] 2022-06-20 11:23
This is probably caused by the mod having to search through all drawers to find the right one. I'll probably have to fix this by using some form of caching, but implementing it will take a while

**Comment by MattiDragon** [comment] 2022-06-23 12:45
Could you try out [the latest dev build](https://github.com/MattiDragon/ExtendedDrawers/releases/tag/dev)? It should be a lot better now

**Comment by MattiDragon** [comment] 2022-06-23 14:58
Closing this now. If the issue persists on 1.18 feel free to reopen. A 1.19 port of the fix is on the way

**Closed by MattiDragon** 2022-06-23 14:58 UTC
Labels: bug, unconfirmed
